# Generated by Django 3.2.4 on 2021-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripreneur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
