# Generated by Django 3.2.4 on 2021-06-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripreneur', '0002_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgriInfo',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
