# Generated by Django 3.2.4 on 2021-06-10 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agripreneur', '0004_agriinfo_farmer_productcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
