# Generated by Django 3.2.4 on 2021-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripreneur', '0008_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agriinfo',
            old_name='product',
            new_name='name',
        ),
        migrations.AddField(
            model_name='agriinfo',
            name='resource',
            field=models.CharField(default='anonymous', max_length=50, null=True),
        ),
    ]
